---
- name: copy tomcat.service file to /etc/system/system
  ansible.builtin.copy:
    src: files/tomcat.service
    dest: /etc/system/system/tomcat.service
    own: root
    group: root
    mode: '0644'