#SPDX-License-Identifier: MIT-0
---
# tasks file for mywebrole
- name: install webserver on debian nodes
  ansible.builtin.apt:
    name: apache2
    state: present
    update_cache: true

- name: ensure apache2 service is running and enabled
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: true