---
# tasks file for mywebrole
- name: Install webserver on RedHat nodes
  ansible.builtin.package:
    name: httpd
    state: present

- name: Ensure httpd service is running
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: yes